[package]
name = "tunein-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tunein"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
clap = "3.2.20"
owo-colors = "3.5.0"
tunein = "0.1.2"
tokio = { version = "1.24.2", features = ["tokio-macros", "macros", "rt", "rt-multi-thread"] }