on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Installing needed dependencies
        run: sudo apt-get install -y libasound2-dev protobuf-compiler
      - name: Running cargo build
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: stable
          args: --locked --release --target x86_64-unknown-linux-gnu
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Packaging final binary
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        shell: bash
        run: |
          cd target/x86_64-unknown-linux-gnu/release
          tar czvf tunein_${{ env.RELEASE_VERSION }}_x86_64-unknown-linux-gnu.tar.gz tunein
          shasum -a 256 tunein_${{ env.RELEASE_VERSION }}_x86_64-unknown-linux-gnu.tar.gz > tunein_${{ env.RELEASE_VERSION }}_x86_64-unknown-linux-gnu.tar.gz.sha256
      - name: Releasing assets
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/tunein_${{ env.RELEASE_VERSION }}_x86_64-unknown-linux-gnu.tar.gz
            target/x86_64-unknown-linux-gnu/release/tunein_${{ env.RELEASE_VERSION }}_x86_64-unknown-linux-gnu.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}